config/routes.rb
Snipit::Application.routes.draw do

  root 'application#landing'
  get '/results' => 'results#index'

  resources :users
  resources :boards
  resources :instances
  get '/languages/:code/snips' => 'languages#index'
  post '/search' => "application#search"
  post '/create_snipit' => 'snipits#create_snipit'
  get '/logout' => 'sessions#logout'

  resources :snips
  resources :sessions, :only => [:new, :create, :destroy]

end

app/models/board.rb
class Board < ActiveRecord::Base
  belongs_to :user
  has_many :instances
  validates :user_id, :presence => true
end

app/models/instance.rb
class Instance < ActiveRecord::Base
  belongs_to :snip
  belongs_to :board

  validates :snip_id, :board_id, :presence => true
end

app/models/language.rb
class Language < ActiveRecord::Base
  has_many :snips

end

app/models/snip.rb
class Snip < ActiveRecord::Base
  include PgSearch
  belongs_to :user
  has_many :instances
  belongs_to :language

  validates :title, :description, :content, :language_id, :presence => true
 	validates :language_id, numericality: { only_integer: true, message: "Must be Chosen" }


  pg_search_scope :search_title_and_content, :against => [:title,:content,:description]
end

app/models/user.rb
require 'bcrypt'

class User < ActiveRecord::Base
  has_many :boards
  has_many :snips
  include BCrypt
  has_secure_password
  include Gravtastic
  gravtastic

  validates :first_name, :last_name, :email, presence: true
  validates :email, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
 layout "application"
 layout "landing_page", :only => "landing"
  def landing
    @languages = Language.all.shuffle[0..8]
  end
  protect_from_forgery with: :exception

  def current_user
    puts "*********ASFa3rara3sfas: #{session[:id].inspect}"
    @current_user ||= User.find_by_id(session[:id])
  end

  def search
    @snips = Snip.search_title_and_content(params[:search]).reverse
    @languages = Language.all.order('name')
    @search_title = "Search Results for: #{params[:search]}"
    @boards = Board.where('user_id = ?', session[:id])
    render "/results/index"
  end

  helper_method :current_user
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  def index
    redirect _to :root unless current_user
    @user = User.find(session[:id])
    @boards = @user.boards
    @languages = Language.all.order('name')
    @search_title = "Your Boards"
    @snips = []
  end

  def show
    redirect _to :root unless current_user
    @user = User.find(session[:id])
    @languages = Language.all.order('name')
    @boards = @user.boards
    @board = Board.find(params[:id])
    @search_title = "Snipits in #{@board.title}"
    @snips = @board.instances.map{|instance| instance.snip }.reverse
  end
end

app/controllers/instances_controller.rb
class InstancesController < ApplicationController
  def create
    # Instance.create!(board_id: params["boardId"], snipit_id: params["snipit_id"] )
  end
end

app/controllers/languages_controller.rb
class LanguagesController < ApplicationController
  layout "application"
  def index
    # all code snipits
    @languages = Language.all.order('name')
    language = Language.find_by_code(params[:code])
    @snips = language.snips.all.reverse
    @search_title = "#{language.name} snips"
    @boards = Board.where('user_id = ?', session[:id])
  end

  def show
    # all code snipits for a given language
  end

  def new
    # @language = Language.new
  end

  def create
    # @language = Language.create
  end

end

app/controllers/results_controller.rb
class ResultsController < ApplicationController
  def index
    @snips = Snip.all.reverse
    @languages = Language.all.order('name')
    @boards = Board.where('user_id = ?', session[:id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by_email(params[:email])
    if @user && @user.authenticate(params[:password])
      session[:id] = @user.id
      redirect_to '/boards'
    else
      flash.now[:login_error] = "Invalid Email/Password Combination"
      # puts "********* #{flash[errors]}"
      render 'new'
    end
  end

  def logout
    session.clear
    redirect_to '/'
  end
end

app/controllers/snipits_controller.rb
class SnipitsController < ApplicationController
  def index
    redirect _to :root unless current_user
    @user = User.find(params[:user_id])
    @snipits = @user.snipits
  end

  def new_snipit
    @options = Language.all.each_with_index.map{|l,i| ["#{l.name}", i]}
  end

  def create
    snipit = current_user.snipits.new(create_params)
    #what is current user?

    if quote.save
      redirect to
    else
      render :new_snipit
    end
  end

  private

  def create_params
    params.require(:quote).permit(:user_id, :language_id, :title, :description, :content)
  end

end

app/controllers/snips_controller.rb
class SnipsController < ApplicationController
  def index
    redirect _to :root unless current_user
    @user = User.find(session[:id])
    @snips = @user.snips.reverse
    @languages = Language.all.order('name')
    @search_title = "Your Snipits"
    @boards = Board.where('user_id = ?', session[:id])
  end

  def new
    @snip = Snip.new
    @languages = Language.all
    @boards = Board.where('user_id = ?', session[:id])
  end

  def create
    puts params
    user = User.find(1)
    user.snips << Snip.create(snip_params)
  end

  private
  def snip_params
    params.require(:snip).permit(:title, :description, :language_id, :content)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.valid?
      @user.save
      flash[:success_sign_up] = "Snipit Account Successfully Created"
      redirect_to new_session_path
    else
      flash.now[:errors] = @user.errors.full_messages
      render 'new'
    end
  end


  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/index.html.erb
<% if session[:id] %>
  <div id='gravatar'>
    <%= image_tag User.first.gravatar_url %>
  </div>
  <div id="dropdown" class="hide">
    <ul>
      <li><%= link_to 'New Snipit', new_snip_path %></li>
      <li><%= link_to 'My Snipits', snips_path %></li>
      <li><a href="/boards">My Boards</a></li>
      <li><%= link_to 'Logout', '/logout' %></li>
    </ul>
  </div>
<% else %>
  <div id='session'>
    <a href="/sessions/new">Login </a>|
    <a href="/users/new"> Signup</a>
  </div>
<% end %>
<div id='logo'>SnipIt</div>
<div id='search'>
  <div id='search_bar'>
    <%= form_tag "/search" do %>
      <%= text_field_tag "search", nil, :placeholder => 'e.g. Javascript Modal' %>
    <% end %>
  </div>
  <div id='language_box'>
    <% @languages.each do |language| %>
      <%= link_to "/languages/#{language.code}/snips" do %>
        <div class='language'>
          <div class='language_img'>
            <%= image_tag(language.code+".png", class: "image_icon") %>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

<script type="text/javascript">
  $('#gravatar').click(function(){
    $('#dropdown').fadeIn();
  });
  $('#dropdown').on('hover',function(){
    $('#dropdown').fadeOut();
  })
</script>

app/views/application/landing.html.erb
<div id="landing_page_background"></div>
<% if current_user %>
  <div id='home_gravatar'>
    <%= image_tag current_user.gravatar_url %>
  </div>
<% else %>
  <div class='session' id="home_session">
    <a href="/sessions/new">Login</a>
    <a href="/users/new">Signup</a>
  </div>
<% end %>

<div id='logo'>&#60;SnipIt&#62;</div>
<div id='search'>
  <div id='search_bar'>
    <%= form_tag "/search" do %>
      <%= text_field_tag "search", nil, :placeholder => 'e.g. Javascript Modal' %>
    <% end %>
  </div>
  <div id='language_box'>
    <% @languages.each do |language| %>
      <%= link_to "/languages/#{language.code}/snips" do %>
        <div class='language'>
          <div class='language_img'>
            <%= image_tag(language.code+".png", class: "image_icon") %>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/boards/index.html.erb
<%= render 'shared/results' %>

app/views/boards/show.html.erb
<%= render 'shared/results' %>

app/views/landing_page/index.erb
<div id='gravatar'></div>
<div id='logo'></div>
<div id='search'>
  <div id='search_bar'>
    <%= form_tag do %>
      <%= text_field_tag(:main_search) %>
      <%= submit_tag("Search"), :style => "display:none" %>
    <% end %>
  </div>
  <div id='language_box'>
    <%@languages.each do |language|%>
      <div class='language'>
        <span class='language_name'>
          <%=language.name%>
        </span>
        <div class='language_img'>
          <% #implement attach file with paperclip %>
        </div>
      </div>
    <%end%>
  </div>
</div>

app/views/landing_page/index.html.erb
<% if session[:id] %>
  <div id='gravatar'>
    <%= image_tag User.first.gravatar_url %>
  </div>
  <div id="dropdown" class="hide">
    <ul>
      <li><%= link_to 'New Snipit', new_snip_path %></li>
      <li><%= link_to 'My Snipits', snips_path %></li>
      <li><a href="/boards">My Boards</a></li>
      <li><%= link_to 'Logout', '/logout' %></li>
    </ul>
  </div>
<% else %>
  <div id='session'>
    <a href="/sessions/new">Login </a>|
    <a href="/users/new"> Signup</a>
  </div>
<% end %>
<div id='logo'>SnipIt</div>
<div id='search'>
  <div id='search_bar'>
    <%= form_tag "/search" do %>
      <%= text_field_tag "search", nil, :placeholder => 'e.g. Javascript Modal' %>
    <% end %>
  </div>
  <div id='language_box'>
    <% @languages.each do |language| %>
        <div class='language'>

          <div class='language_img'>
             <%= link_to image_tag(language.code+".png", class: "image_icon"), "/languages/#{language.code}/snips" %>
          </div>
        </div>
    <% end %>
  </div>
</div>

<script type="text/javascript">
  $('#gravatar').click(function(){
    $('#dropdown').fadeIn();
  });
  $('#dropdown').on('hover',function(){
    $('#dropdown').fadeOut();
  })
</script>

app/views/layouts/_footer.erb
</body>
</html>

app/views/layouts/_footer.html.erb
</body>
</html>

app/views/layouts/_header.erb
<!DOCTYPE html>
<html>
<head>
  <title>Snipit</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

app/views/layouts/_header.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Snipit</title>
  <%= include_gon %>
  <%= javascript_include_tag "underscore-min.js" %>
  <%= javascript_include_tag "jquery-1.9.0.js" %>
  <%= stylesheet_link_tag    "application", "monospace_font/stylesheet.css", media: "all", "data-turbolinks-track" => true %>

  <%= csrf_meta_tags %>
</head>
<body>

app/views/layouts/_topbar.erb
<nav id="topbar">
  <div id="logo">
    <img src="/logo.png" alt="SnipIt">
  </div>

  <div id="topbar_search">
    <%= form_tag do %>
      <%= text_field_tag(:topbar_search_field), placeholder: 'Search' %>
      <%= submit_tag("Search"), :style => "display:none" %>
    <% end %>
  </div>

  <div id="user_info">
    <% if session[:id] %>
      <div id="gravatar"></div>
    <% else %>
      <a href="/signup" id="singup">Sign Up</a>
      <a href="/login" id="login">Login</a>
    <% end %>
  </div>
</nav>

app/views/layouts/application.erb
<%=  render 'header' %>
<%=  render 'topbar' %>
<%= yield %>
<%= render 'footer' %>

app/views/layouts/application.html.erb
<%= render partial: 'layouts/header' %>

<%= render partial: 'shared/navbar' %>


<%= yield %>
<%= render partial: 'shared/dropdown_and_script' %>

<%= render partial: 'layouts/footer' %>

app/views/layouts/landing_page.erb
<%= render 'header' %>
<%= yield %>
<%= render 'footer' %>

app/views/layouts/landing_page.html.erb
<%= render partial: 'layouts/header' %>

<%= yield %>

<div id="landing_dropdown">
  <%= render 'shared/dropdown_and_script' %>  
</div>

<%= render partial: 'layouts/footer' %>

app/views/shared/_board_modal.html.erb
<div id="board_modal">
  <div class="content" id="add_to_board_modal">
    <%= text_field_tag :new_board, nil, :placeholder => "New Board" %>
    <div id="user_boards">
      <ul>
        <% @boards.each do |board| %>
          <%= link_to '#', :class => "chosen_board", :id => board.id do %>
            <li><%= board.title %></li>
          <% end %>
        <% end %>
      </ul>
    </div>
  </div>
  <div id="second_mask"></div>
</div>

app/views/shared/_dropdown_and_script.html.erb
<div class="dropdown hide">
  <ul>
    <%= link_to snips_path do %>
      <li>My Snipits</li>
    <% end %>
    <%= link_to '/boards' do %>
      <li>My Boards</li>
    <% end %>
    <%= link_to '/logout' do %>
      <li>Logout</li>
    <% end %>
  </ul>
</div>

<script type="text/javascript">
  $('#home_gravatar, #site_wide_gravatar').click(function(e){
    if($(e.target).attr('id') === "site_wide_gravatar") { //place dropdown in the correct location if not on the landing page
      $(".dropdown").css('right',($(window).width()-1000) / 2)
    };
    $('.dropdown').fadeIn();
  });
  $(document).mouseup(function (e){
    var container = $(".dropdown");
    if (!container.is(e.target) && container.has(e.target).length === 0){ //everywhere except inside the dropdown menu
      container.fadeOut('fast');
    }
  });
</script>

app/views/shared/_modal_holder.html.erb
<div class='modalHolder'>
  <div class='content'>
    <div id="show_card">
      <button id='add_to_board_button'>&#60;&#62;</button>
      <div id="content"></div>
    </div>
  </div>
  <div class='mask'></div>
</div>

app/views/shared/_navbar.html.erb
<nav>
  <div id="nav_container">
    <%= link_to '<SnipIt>', root_path, :id => 'logo_nav' %>
    <%= form_tag('/search') do %>
      <%= text_field_tag "search" ,nil, :placeholder => "Search", :id =>  'query'  %>
    <% end %>
    <% if current_user %>
      <span class="right_hand_navigation">
        <%= link_to new_snip_path do %>
          <div id="new_snipit_link"></div>
        <% end %>
        <%= image_tag current_user.gravatar_url, :id => 'site_wide_gravatar' %>
      </span>
	  <% else %>
	   	<span class="right_hand_navigation session">
        <%= link_to 'Login', new_session_path %>
        <%= link_to 'Signup', new_user_path %>
 			</span>
    <% end %>
  </div>
</nav> 

app/views/shared/_navbar_signed_in.html.erb
<nav>
  <div id="nav_container">
    <%= link_to '<SnipIt>', root_path, :id => 'logo_nav' %>
    <%= form_tag('/search') do %>
      <%= text_field_tag "search" ,nil, :placeholder => "Search", :id =>  'query'  %>
    <% end %>
    <% if current_user %>
	    <div id='site_wide_gravatar'>
	      <%= image_tag current_user.gravatar_url %>
	    </div>
	  <% else %>
	   	<div id='session'>
		    <a href="/sessions/new">Login </a>|
		    <a href="/users/new"> Signup</a>
 			</div>
    <% end %>
  </div>
</nav> 

app/views/shared/_results.html.erb
<div id='container'>
  <div id='languages'>
    <ul>
      <% @languages.each do |language| %>
        <%= link_to "/languages/#{language.code}/snips" do %>
          <li><%= language.name %></li>
        <% end %>
      <% end %>
    </ul>
  </div>
  <div id="cards">
    <h2 id="search_title"><%= @search_title %></h2>
    <%lan = []%>
    <% @snips.each do |c| %>
      <%= content_tag :div, class: "cards_data card", data: {snips:c} do %>

        <h4 class="card_title">
          <span class="card_language">
            <%= c.language.name %> -
          </span>
          <%= c.title %>
        </h4>
        <p class="card_description"><%= truncate(c.description, length: 130) %></p>
        <% lan << c.language_id %>
      <%end%>
    <%end%>
    <% if current_page?(boards_path) %>
      <% @boards.each do |board| %>
        <%= link_to board_path(board) do %>
          <div class="board">
            <h4 class="board_title"><%= board.title %></h4>
          </div>
        <% end %>
      <% end %>
    <% end %>
  </div>
</div>


<%= render 'shared/modal_holder' %>
<%= render 'shared/board_modal' %>

<%= javascript_include_tag "ace/ace" %>
<%= javascript_include_tag "application" %>

<script type='text/template' class='template'>
    <h3 class='modal_card_title' id='<%%= v.id %>'><%%=v.title%></h3>
    <p class='modal_card_description'><%%=v.description%></p>
    <div id="results_editor"></div>
</script>

<script type="text/javascript">
  // $(".chosen_board").on('click', function(e){
    // var data = {boardName: $(e.target).html(), snipit_id: $(".modal_card_title").attr('id')};
    // $.ajax({
    //   url: '/instances',
    //   type: 'post',
    //   data: (data),
    //   success: function(){
    //     console.log(data);
    //   },
    //   error: function(){
    //     console.log(data);
    //   }
    // });
  // })
</script>


    

app/views/sinpits/snipits.erb
<div id="languages_sidebar">
  <ul>
    <% @languages.each do |language| %>
      <li><a href="/<%= language.name %>"><%= language.name %></a></li>
    <% end %>
  </ul>
</div>
<div id="results">
  <% @snipits.each do |snipit| %>
    <div class="snipit_card" id="<%= snipit.id %>">
      <span class="snipit_card_title"><%= snipit.title %></span>
      <div class="snipit_card_description truncate"><%= snipit.description %></div>
    </div>
  <% end %>
</div>

<div id="snipit_modal" class="hidden">
  <div id="snipit_modal_snipit"><img src="/snipit.png" alt="Snipit"></div>
  <div id="snipit_modal_description"><%= snipit.description %></div>
  <pre class="<%= snipit.language %>">
    <div id="snipit_modal_code"><%= snipit.content %></div>
  </pre>
</div>

<div id="board_modal" class="hidden">
  <%= form_tag do %>
    <%= text_field_tag(:board), :placeholder: "New Board" %>
    <%= submit_tag("Create"), :style => "display:none" %>
  <% end %>
  <ul>
    <% @boards.each do |board| %>
      <li id="board_<%= board.id %>"><%= board.name %></li>
    <% end %>
  </ul>
</div>

app/views/snips/_editor.html.erb
<div id="editor"></div>

<%= javascript_include_tag "ace/ace" %>
<%= javascript_include_tag "create_snip" %>

app/views/snips/create.js.erb
<% if @redirect %>
	location.href = 'http://localhost:3000' + "<%= escape_javascript(@redirect) %>";
<% end %>


var errors = gon.errors;
$.each(errors, function(key, value) {
	if (key == 'language_id') {
		$('#language_error').html(value);
	};
	$('#' + key).attr('placeholder', value);
	$('#' + key).addClass('create-error');

	if (editor.getSession().getValue() == "") {
		$('#content_error').html('Enter Some Code!')
	}
});

app/views/snips/new.html.erb
<div id="container">
  <div id="new_snipit_container">
    <%= form_for(:snip, url: snips_path, html: {id: 'new_snip_form'}) do |f| %>
      <p><%= f.text_field :title,  :placeholder => 'Title', :id => 'title' %></p>
      <p><%= f.text_field :description, :placeholder => 'Description', id: 'description' %></p>

      <p><%= f.select(:language_id, options_for_select(@languages.map { |l| [l.name, l.id, {"data-code" => l.code}] }.insert(0,'Choose Language')),{},{:class => 'option_select', :selected => 'Language'})%>
        <span id='language_error'></span>
      </p>
      <%= f.hidden_field :content %>
      <span id='content_error'></span>
      <%= render partial: 'editor' %>

      <%= submit_tag 'Create New Snipit', :id => 'create_new_snipit', :class =>'submit_button'%> <!-- onclick popup modal to choose what board to put it in -->
    <% end %>
  </div>
</div>

app/views/snips/show.html.erb
<%= render partial: 'shared/results' %>

app/views/users/login.html.erb
<div>
  <%= form_tag("/sessions", method: "post") do |f| %>
    <%= text_field_tag :email %>
    <%= password_field_tag :password %>
    <%= submit_tag "Sign in" %>
  <% end %>
</div>

app/views/users/new.html.erb
<div class="session_form">
  <div id="flash_signup" class="flash">
    <% if flash[:errors] %>
        <div class='errors'>
          <% flash[:errors].each do |error| %>
            <%= error %><br>
          <% end %>
        </div>
    <% end %>
  </div>
  <%= form_for(@user, url: users_path, html: {class: "form-style"}) do |f| %>
    <%= f.text_field :first_name, :placeholder => 'First Name' %>
    <%= f.text_field :last_name, :placeholder => 'Last Name' %>
    <%= f.text_field :email, :placeholder => 'Email' %>
    <%= f.password_field :password, :placeholder => 'Password' %>
    <%= f.password_field :password_confirmation, :placeholder => 'Confirmation' %>
    <%= f.submit "Create my account", :class => "submit_button" %>
  <% end %>
</div>